### ISSUE TITLE
Any Plan to Support for Swift4.0?

### ISSUE THREAD

**Issue by EricYellow** [RxSwiftCommunity/RxGRDB#14]
Hi @groue , Thx for your awesome work . Do you have any plan to update the RxGRDB to Swift4.0?

**Comment by groue** [comment]
Hello @EricYellow. Of course there is a plan for Swift 4! Didn't you notice the pull request #13 😉 ?

**Comment by groue** [comment]
Happy RxGRDB!

**Comment by groue** [comment]
Swift 4 support has landed in the new v0.7.0 version
