### ISSUE TITLE
RxGRDB doesn't fetch results in Test Target

### ISSUE THREAD

**Issue by freak4pc** [RxSwiftCommunity/RxGRDB#33]
Hey @groue :) I feel like I'm bothering you more than usual in the last few days, but I think I've found a possible minor bug in RxGRDB specifically.

In my test target, I inject an in-memory `DatabaseQueue` to fetch some order information. I noticed that `fetchOne` never emits anything **specifically in test targets**, but it does in the main target. This is even though the order exists (as confirmed by imperatively fetching it). 

I tried switching from in-memory to path-based but that didn't provide any change

```swift
print("queue -> \(databaseQueue)")

let orderObj = try! databaseQueue.read { db in
    return try Order.fetchOne(db, key: orderID)
}

print("order -> \(orderObj)")

let order = Order.filter(key: orderID)
    .rx.fetchOne(in: databaseQueue)
    .debug("fetch")
    ... more irrelevant code down here ...
```

Prints out

```
queue -> GRDB.DatabaseQueue
order -> Optional(MyApp.Order(id: "CE37F0B2-E25E-4898-942D-8DC5D00C5D0F", ... more info ...))
fetch -> subscribed
```

As you can see, reading from the database queue imperatively returns the correct object, but observing with `fetchOne` doesn't seem to product the desired effect.

Even if the object wouldn't exist, I would expect a `nil` emission instead of nothing. 

Any thoughts on what could cause this? 

Thanks!
Shai.

**Comment by freak4pc** [comment]
OK just realized my mistake. 

Sometimes all you need is a GitHub issue for a rubber ducky. Sorry for the confusion! :) 

<img src="https://media0.giphy.com/media/u6abG1EmZciv6/giphy.gif" />

**Comment by groue** [comment]
Thanks for the lovely duck 😸
