### ISSUE TITLE
UI bindings?

### ISSUE THREAD

**Issue by robert-cronin** [RxSwiftCommunity/RxGRDB#35]
This might be something I have missed in the documentation and sorry if it is.
I know in RxSwift, you can bind a UITextField to variable via:

```
textField.rx.text.orEmpty
.bind(to: self.someVariable)
.addDisposableTo(disposeBag)
```

My question is, does RxGRDB have a native way to handle a binding from a SQLite request to a textiField or should I just use a combination of the two?

**Comment by groue** [comment]
Hello @robert-cronin,

Your sample code looks like you want to drive the content of the database from a textfield. But is it really the case? Don't you want instead to have the content of the database drive the UI?

If this is the case, then the code below, inspired from [RxSwift sample code](https://github.com/ReactiveX/RxSwift/blob/master/Documentation/Examples.md#simple-ui-bindings), should work as expected:

```swift
let allPlayerRequest = Player.all()
allPlayerRequest.rx
    .fetchCount(in: dbQueue)
    .map { "\($0) players" }
    .bind(to: playerCountLabel.rx.text)

let maximumScoreRequest = Player
    .select(max(Column("score")))
    .asRequestOf(Int.self)
maximumScoreRequest.rx
    .fetchCount(in: dbQueue)
    .map { "\($0)" }
    .bind(to: maximumScoreLabel.rx.text)
```

Now of course, you may sometimes need to update several UI elements on each database change. For example, if you track a single record, you may write something like:

```swift
Player.filter(key: 1).rx
    .fetchOne(in: dbQueue)
    .subscribe(onNext: { [weak self] player in
        if player = player {
            // Player 1 has been updated
        } else {
            // Player 1 has been deleted
        }
    })
```

**Comment by robert-cronin** [comment]
Thanks groue!
I have tried to implement a simple binding but keep coming up with the following error:
`Fatal error: could not convert database value NULL to String`

I have a flights table with an aircraft id i want to bind to a textfield, my implementation looks like this:
```
FLIGHTS.filter(sql: "FLIGHT_ID = '\(currentFlightID)'").rx
    .fetchOne(in: dbQueue)
    .map { $0?.AC_ID ?? "" }
    .bind(to: aircraftIdText.rx.text)
```
Any ideas on why this is the case given that I know AC_ID is not null?

Thanks!

**Comment by groue** [comment]
Oh, and I have to give you an extra advice when I read:

```
FLIGHTS.filter(sql: "FLIGHT_ID = '\(currentFlightID)'")
```

You should really stop embedding raw values in SQL, and start using arguments instead:

```
FLIGHTS.filter(sql: "FLIGHT_ID = ?", arguments: [currentFlightID})
```

Another valid option:

```
FLIGHTS.filter(Column("FLIGHT_ID") == currentFlightID)
```

Sorry if I sound like a pontificating teacher, but this should be a **reflex**. See [Avoiding SQL Injection](https://github.com/groue/GRDB.swift#avoiding-sql-injection) for more information.

**Comment by robert-cronin** [comment]
Yes, I felt a bit nervous writing it like that! It is all functioning as expected now, this library has saved me pages of code! Thanks for writing it 😄
