### ISSUE TITLE
why not support carthage?

### ISSUE THREAD

**Issue by phpmaple** [RxSwiftCommunity/RxGRDB#40]
When I build scheme use Carthage, it show error

**Comment by groue** [comment]
Hello @phpmaple,

Carthage takes too much time to support. Listen to fellow developers who have errors, help them fix those errors, discover weird glitches with Carthage itself, see errors leave and come back, etc. It's an unbearable time sink for the main maintainer of GRDB and RxGRDB: myself. So one day I [dropped Carthage support](https://github.com/groue/GRDB.swift/blob/master/CHANGELOG.md#01040) and this was the best decision I could take.

This is not the end of the story: some fellow developers have recently helped GRDB moving forward on the Carthage subject: see https://github.com/groue/GRDB.swift/pulls?utf8=✓&q=Carthage+

Maybe you, or somebody else, will bring Carthage to RxGRDB as well.

Meanwhile, I suggest you just use CocoaPods.
