### ISSUE TITLE
Experiencing slowness in queries when upgrading from 0.12.0 to 0.13.0

### ISSUE THREAD

**Issue by kochavi-daniel** [RxSwiftCommunity/RxGRDB#50]
When we upgraded from 0.12.0 to 0.13.0 we started experiencing slowness in simple queries. What can I do to troubleshoot this or what more information could I provide?

**Comment by groue** [comment]
Hello @kochavi-daniel,

Could you please provide more details? The kind of requests you observe, the kind of observable you create, what is this "slowness" you are experiencing? This will greatly help anyone who wants to help you. Please be precise as you can.

**Comment by groue** [comment]
No news is good news. Happy RxGRDB, @kochavi-daniel!
