### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by denisw** [RxSwiftCommunity/RxGRDB#53]
With Xcode now having built-in support for the Swift Package Manager, it would be nice if this project had a `Package.swift` so that it is installable using that (both RxJS and GRDB already have Swift Package Manager support).

**Comment by groue** [comment]
Hello @denisw,

This is a very good idea! Would you fancy setting up a pull request?

**Comment by denisw** [comment]
@groue I created #54, which works fine for me on Xcode 11 with Swift 5.

**Comment by groue** [comment]
#60 has been merged. Next release comes soon.

**Comment by groue** [comment]
SPM support is available in v0.18.0
