### ISSUE TITLE
Support SQLCipher

### ISSUE THREAD

**Issue by groue** [RxSwiftCommunity/RxGRDB#6]
See initial request from @hartbit: https://github.com/groue/GRDB.swift/issues/211

**Comment by groue** [comment]
@hartbit, update your Podfile!

```ruby
pod 'RxGRDB/GRDBCipher'
```

**Comment by groue** [comment]
Nope: I could not push the `v0.2.0` tag to this repository, and `pod trunk push` fails. @freak4pc, sorry to disturb you again: do you know how I can add a tag to this repo?

**Comment by hartbit** [comment]
❤️

**Comment by groue** [comment]
Until somebody is able to publish the new pod version, the new features can be accessed via https://github.com/groue/RxGRDB:

```ruby
pod 'RxGRDB/GRDBCipher', :git => 'https://github.com/groue/RxGRDB.git', :tag => '0.2.0'
```

**Comment by freak4pc** [comment]
Hey @groue , You should be the author / admin of this repo. 
Did you try just doing a `git tag 0.2.0 && git push --tags origin` ?

**Comment by groue** [comment]
Good idea: pushing via command-line gave more information:

```
ERROR: Sorry, but @RxSwiftCommunity has blocked access to SSH keys created by some third-party applications. Your key was created before GitHub tracked keys created by applications, so we need your help.
...
```

Now my keys are OK, the tag v0.2.0 is online, and the CocoaPods is on its way. Thanks @freak4pc!
