### ISSUE TITLE
Fix podspec SPM support status

### ISSUE THREAD

**Issue by brunomunizaf** [RxSwiftCommunity/RxGRDB#67]
It seems that the podspec says that RxGRDB doesn't support SPM.
![Screen Shot 2020-12-01 at 5 22 03 PM](https://user-images.githubusercontent.com/12559440/100792663-be72cd00-33f9-11eb-87cb-d1d3e7ad7453.png)

**Comment by groue** [comment]
@brunomunizaf, thanks for spotting the problem, but I guess the problem lies in the CocoaPods website. This is where this issue should be raised.
