### ISSUE TITLE
Compiling for iOS 10.0, but module 'GRDB' has a minimum deployment target of iOS 11.0

### ISSUE THREAD

**Issue by ksemianov** [RxSwiftCommunity/RxGRDB#68]
After the recent increase in the iOS deployment target of GRDB.swift, RxGRDB doesn't compile

```
Compiling for iOS 10.0, but module 'GRDB' has a minimum deployment target of iOS 11.0
```

Probably, the deployment target for RxGRDB should be raised as well

GRDB.swift (5.12.0)
RxGRDB (2.0.0)
Xcode 13.0 (13A233)
COCOAPODS: 1.11.2

**Comment by groue** [comment]
> Probably, the deployment target for RxGRDB should be raised as well 

This does not make sense: RxGRDB 2.0 declares a dependency on GRDB 5.0+, which targets iOS 10+. There is no reason RxGRDB 2.0 could not work with GRDB 5.12+ and iOS 11+.

To me, the "Compiling for iOS 10.0" message tells that your app is requiring iOS 10.0, and this is where you should act. 
Did you check your `IPHONEOS_DEPLOYMENT_TARGET`? Did you check if your Podfile mentions `platform :ios, '11.0'`?

**Comment by ksemianov** [comment]
`IPHONEOS_DEPLOYMENT_TARGET` is set to `11.0`
Podfile contains line `platform :ios, '11.0'`

The latest GRDB.swift (5.12.0) targets iOS `11.0`. While the latest RxGRDB (2.0.0) targets iOS `10.0`. Swift cannot do `import GRDB` in RxGRDB, because it requires at least `11.0` to do so

Do you need a minimal repro?

**Comment by groue** [comment]
This sounds like a bug in CocoaPods to me.

**Comment by ksemianov** [comment]
Well, it's a limitation of CocoaPods. When Pod author writes `s.ios.deployment_target = '10.0'` it will translate to compiling with exactly `10.0` iOS SDK when `pod install` generates `.xcworkspace`. It doesn't check that RxGRDB dependency has a higher deployment target and set `11.0` instead

Here is an example to reproduce the error https://github.com/ksemianov/RxGRDB.CompilationError

**Comment by groue** [comment]
I'd appreciate a link to the issue about this "limitation" in the Cocoapods repo, thank you.

**Comment by groue** [comment]
...Or maybe the RxGRDB podspec should be changed in order to specify a _minimum_ iOS version. But a straight bump is not supposed to be necessary, and I'm pretty sure this annoyance has been discussed at length on the CocoaPods repo. If you don't find those discussions online I will, but your help is appreciated.

**Comment by ksemianov** [comment]
I think this reply is relevant https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-356202182

There is a workaround to specify the deployment target in Podfile post install hook:

```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'RxGRDB'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end
```

**Comment by ksemianov** [comment]
Submitted an issue to CocoaPods in case they decide to make an enhancement https://github.com/CocoaPods/CocoaPods/issues/10968

**Comment by groue** [comment]
Thanks @ksemianov, I'll do my best shortly, based on your excellent input 👍

**Comment by hainayanda** [comment]
It's happening in SPM too, it's because the GRDB is already updating its platform from iOS 10 to iOS 11 (starting from 5.12.0), and since _RxGRDB_ is dependent on > 5.0.0, then SPM will get the latest version which already bumped its platform to iOS 11. One way to fix the error is by explicitly add _GRDB_ as project dependency and set its version to exactly 5.11.0 or lower. Then _RxGRDB_ will be forced to use it.

**Comment by zefender** [comment]
Hi @groue! I'm also facing the same issue with min iOS version, any progress on a new version? 
Looking forward for your update, 
thanks!

**Comment by groue** [comment]
🚀 There we go, v2.1.0 has shipped!
